#!/bin/bash
core() {
	cat /proc/cpuinfo | grep processor -c
}


cd /usr/src
wget http://garr.dl.sourceforge.net/project/imagemagick/6.9.0-sources/ImageMagick-6.9.0-3.tar.gz
tar xvf ImageMagick-6.9.0-3.tar.gz
cd ImageMagick-6.9.0-3/
./configure --with-modules \--with-imagick=/opt/local
make -j $core
checkinstall -D -y \
  --install=no \
  --fstrans=no \
  --reset-uids=yes \
  --pkgname=imagemagick \
  --pkgversion=6.9.0-0 \
  --pkglicense=GPL \
  --maintainer="lagout " \
  --pakdir=/usr/src/deb \
  --nodoc

cd /usr/src/deb

dpkg -i imagemagick*.deb
