#!/bin/bash
cd /usr/src
wget http://kent.dl.sourceforge.net/project/imagemagick/6.8.9-sources/ImageMagick-6.8.9-6.tar.gz
tar xvf ImageMagick-6.8.9-6.tar.gz
cd ImageMagick-6.8.9-5/
./configure --with-modules \--with-imagick=/opt/local
make
make install
