#!/bin/bash
cd /usr/src
wget http://garr.dl.sourceforge.net/project/imagemagick/6.9.0-sources/ImageMagick-6.9.0-0.tar.gz
tar xvf ImageMagick-6.9.0-0.tar.gz
cd ImageMagick-6.9.0-0/
./configure --with-modules \--with-imagick=/opt/local
make
make install
