#!/bin/bash
execPath=$(readlink -f $(dirname $0))
apt-get build-dep openssl -y
dpkg -r --force-depends libssl1.0.0
mkdir /usr/src/ssl
cd /usr/src/ssl
wget http://www.openssl.org/source/openssl-1.0.1i.tar.gz
tar zxvf openssl-1.0.1i.tar.gz
cd openssl-1.0.1i


./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         shared                \
         zlib-dynamic &&
make
make install
bash $execPath/ca-cert-nstall

exit 0


