#!/bin/bash
execPath=$(readlink -f $(dirname $0))
#les dependence php
echo  "instaling dependancies "
apt-get install -y build-essential  autoconf libtool libxml2 libxml2-dev  libcurl4-gnutls-dev libbz2-1.0 libbz2-dev libjpeg-dev libpng12-dev libfreetype6 libfreetype6-dev libldap-2.4-2 libldap2-dev libmcrypt4 libmcrypt-dev libmysqlclient-dev libxslt1.1 libxslt1-dev libxt-dev libfreetype6 libicu-dev libcurl3 libonig2 libqdbm14 libt1-5 libvpx1 libxpm4 
#compilation de php
echo  "compilation of php"
	mkdir /usr/src/php
 
cd /usr/src/php 
	wget http://be2.php.net/distributions/php-5.5.20.tar.gz
	tar zxvf php-5.5.20.tar.gz 

cd php-5.5.20
./configure  --enable-fpm \
	--with-fpm-user=nginx \
	--enable-pdo=shared \
	--with-pdo-mysql=shared \
	--enable-sockets \
	--enable-soap \
	--enable-ftp \
	--enable-wddx \
	--enable-pcntl \
	--enable-soap \
	--enable-bcmath \
	--enable-mbstring \
	--enable-dba \
	--enable-gd-native-ttf \
	--enable-zip \
	--enable-calendar \
	--with-mysql=shared \
	--with-mysqli=shared \
	--with-pdo-sqlite=shared \
	--with-iconv \
	--with-zlib \
	--with-bz2 \
	--with-gettext \
	--with-xmlrpc \
	--with-openssl=/usr \
	--with-mhash \
	--with-mcrypt \
	--with-xsl \
	--with-curl \
	--with-pcre-regex \
	--with-gd=shared \
	--with-freetype-dir=/usr/lib/x86_64-linux-gnu/ \
	--with-config-file-path=/usr/local/etc/php/cgi \
	--with-config-file-scan-dir=/usr/local/etc/php/mods-available

make  

checkinstall -D -y \
	--install=no \
	--fstrans=no \
	--reset-uids=yes \
	--pkgname=php-fpm \
	--pkgversion=5.5.20 \
	--pkglicense=GPL \
	--pakdir=/usr/src/deb  \
	--maintainer="lagout " \
	--nodoc

cd /usr/src/deb
dpkg -i php-fpm*.deb

cd $execPath
	cp  -r ../config/php/php5 /usr/local/etc/php
	cp ../config/php/init.d.php-fpm /etc/init.d/php-fpm
	chmod +x /etc/init.d/php-fpm

sleep 10

exit 0
