#! /bin/sh
VERSION=1.0.1t
execPath=$(readlink -f $(dirname $0))



apt-get build-dep openssl -y
mkdir /usr/src/ssl
cd /usr/src/ssl
wget  --no-check-certificate  http://www.openssl.org/source/openssl-${VERSION}.tar.gz
tar zxvf openssl-${VERSION}.tar.gz
cd openssl-${VERSION}


./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         shared                \
         zlib-dynamic 
make depend
make
checkinstall -D -y \
	--install=no \
	--fstrans=no \
	--reset-uids=yes \
	--pkgname=openssl \
	--pkgversion=${VERSION} \
	--pkglicense=GPL \
	 --pakdir=/usr/src/deb  \
	--maintainer="lagout " \
	--nodoc

cd /usr/src/deb

dpkg -i openssl*.deb

bash $execPath/ca-cert-nstall




