#!/bin/bash

execPath=$(readlink -f $(dirname $0))

apt-get build-dep openssl -y
mkdir /usr/src/ssl
cd /usr/src/ssl
wget http://www.openssl.org/source/openssl-1.0.1k.tar.gz
tar zxvf openssl-1.0.1k.tar.gz
cd openssl-1.0.1k


./config --prefix=/usr         \
         --openssldir=/etc/ssl \
         shared                \
         zlib-dynamic &&
make
checkinstall -D -y \
	--install=no \
	--fstrans=no \
	--reset-uids=yes \
	--pkgname=openssl \
	--pkgversion=1.0.1j \
	--pkglicense=GPL \
	 --pakdir=/usr/src/deb  \
	--maintainer="lagout " \
	--nodoc

cd /usr/src/deb

dpkg -i openssl*.deb

bash $execPath/ca-cert-nstall

exit 


