#! /bin/sh
execPath=$(readlink -f $(dirname $0))

apt-get -y install libpcre3-dev  build-essential autoconf libtool
echo  "creating  nginx's directories"
	mkdir -p /usr/local/nginx/{conf.d,sites-available,sites-enabled}
	mkdir /var/log/nginx
	mkdir -p /var/lib/nginx/{body,proxy,fastcgi}
	mkdir -p /var/cache/nginx/{tmp,cached}
	
echo "Creating user nginx"
	useradd -c nginx -d /usr/local/nginx -M -r -s /bin/false -u 755  nginx
mkdir -p /usr/src/nginx
cd /usr/src/nginx 
echo "download and compilation"
	wget http://nginx.org/download/nginx-1.8.1.tar.gz -O nginx.tar.gz
	tar zxvf nginx.tar.gz
cd  nginx-1.8.1

./configure --user=nginx \
	--group=nginx \
	--with-md5=/usr/lib \
	--with-http_ssl_module \
	--with-http_gzip_static_module \
	--with-http_realip_module \
	--with-http_stub_status_module \
	--with-http_flv_module \
	--with-pcre \
	--without-mail_pop3_module \
	--without-mail_imap_module \
	--without-mail_smtp_module \
	--with-http_degradation_module \
	--with-debug 

make 
checkinstall -D -y \
	--install=no \
	--fstrans=no \
	--reset-uids=yes \
	--pkgname=nginx \
	--pkgversion=1.8.1 \
	--pkglicense=GPL \
	--pakdir=/usr/src/deb  \
	--maintainer="lagout " \
	--nodoc

cd /usr/src/deb

dpkg -i nginx*.deb

cd $execPath
	#cp ../config/nginx/nginx  /etc/init.d/nginx
	cp ../config/nginx/logorate-nginx /etc/logrotate.d/nginx
	cp ../config/systemd/nginx.service  /etc/systemd/system/multi-user.target.wants/
	


mv  /usr/local/nginx/conf/mime.types.default  /usr/local/nginx/conf/mime.types
mv  /usr/local/nginx/conf/nginx.conf.default    /usr/local/nginx/conf/nginx.conf
mv /usr/local/nginx/conf/scgi_params.default   /usr/local/nginx/conf/scgi_params
mv /usr/local/nginx/conf/fastcgi.conf.default   /usr/local/nginx/conf/fastcgi.conf


chown -R nginx /usr/local/nginx/
chown root:root /etc/logrotate.d/nginx
	#chmod +x /etc/init.d/nginx
	systemctl daemon-reload
	systemctl start nginx.service
sleep 20


