#! /bin/sh
execPath=$(readlink -f $(dirname $0))
#les dependence php
echo  "instaling dependancies "
apt-get install -y build-essential  autoconf libtool libxml2 libxml2-dev  libcurl4-gnutls-dev libbz2-1.0 libbz2-dev libjpeg-dev libpng12-dev libfreetype6 libfreetype6-dev libldap-2.4-2 libldap2-dev libmcrypt4 libmcrypt-dev libmysqlclient-dev libxslt1.1 libxslt1-dev libxt-dev libfreetype6 libicu-dev libcurl3 libonig2 libqdbm14 libvpx1 libxpm4 libvpx-dev libxpm-dev libgmp10 libgmp-dev
#compilation de php
ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/include/gmp.h 
echo  "compilation of php"
	mkdir /usr/src/php
 
cd /usr/src/php 
	wget http://be2.php.net/distributions/php-5.6.19.tar.gz
	tar zxvf php-5.6.19.tar.gz 

cd php-5.6.19
./configure  --enable-fpm \
	--with-fpm-user=nginx \
	--enable-pdo=shared \
	--with-pdo-mysql=shared \
	--enable-sockets \
	--enable-soap \
	--enable-ftp \
	--enable-wddx \
	--enable-pcntl \
	--enable-bcmath \
	--enable-mbstring \
	--enable-dba \
	--enable-gd-native-ttf \
	--with-gmp=/usr/include/x86_64-linux-gnu/ \
	--enable-intl \
	--with-png-dir=shared \
	--enable-zip \
	--enable-calendar \
	--with-mysql=shared \
	--with-mysqli=shared \
	--with-pdo-sqlite=shared \
	--with-iconv \
	--with-zlib \
	--with-bz2 \
	--with-gettext \
	--with-xmlrpc \
	--with-openssl=/usr \
	--with-mhash \
	--with-mcrypt \
	--with-xsl \
	--enable-zip \
	--with-regex=php \
	--with-pic \
	--with-layout=GNU \
	--enable-sysvsem \
	--enable-sysvshm \
	--with-mhash=yes \
	--enable-shmop \
	--with-iconv \
	--enable-exif \
	--enable-sysvmsg \
	--with-curl \
	--with-pcre-regex \
	--with-gd=shared \
	--with-vpx-dir=/usr/lib/x86_64-linux-gnu/ \
	--with-jpeg-dir=/usr/lib/x86_64-linux-gnu/ \
	--with-xpm-dir=/usr/local/lib/ImageMagick-6.9.0/modules-Q16/coders/ \
	--with-freetype-dir=/usr/lib/x86_64-linux-gnu/ \
	--with-config-file-path=/etc/php/cgi \
	--with-config-file-scan-dir=/etc/php/mods-available


make  

checkinstall -D -y \
	--install=no \
	--fstrans=no \
	--reset-uids=yes \
	--pkgname=php-fpm \
	--pkgversion=5.6.19 \
	--pkglicense=GPL \
	--pakdir=/usr/src/deb  \
	--maintainer="lagout " \
	--nodoc

cd /usr/src/deb
dpkg -i php-fpm*.deb

cd $execPath
	cp  -r ../config/php/php5  /etc/php
	cp ../config/php/init.d.php-fpm /etc/init.d/php-fpm
	chmod +x /etc/init.d/php-fpm
	cp ../config/systemd/php-fpm.service   /etc/systemd/system/multi-user.target.wants/

systemctl enable php-fpm.service
systemctl start php-fpm.service

sleep 10


