#! /bin/sh
VERSION=5.5.53
execPath=$(readlink -f $(dirname $0))

apt-get build-dep mysql-5.5 -y
apt-get install -y libncurses5-dev cmake #for raspbian 
	echo "creating MariaDB's directories"
mkdir /usr/local/mysql
mkdir /var/run/mysqld
mkdir /usr/src/maria
	echo  "copy repository in  /usr/src/maria and compilation"
cd /usr/src/maria 
	 # copy repository in  /usr/src/maria
wget https://downloads.mariadb.org/interstitial/mariadb-${VERSION}/source/mariadb-${VERSION}.tar.gz
	tar zxvf mariadb-${VERSION}.tar.gz
cd /usr/src/maria/mariadb-${VERSION}
	BUILD/autorun.sh
	./configure
	make verbose=1
		checkinstall -D -y \
		--install=no \
		--fstrans=no \
		--reset-uids=yes \
		--pkgname=mariadb \
		--pkgversion=${VERSION} \
		--pkglicense=GPL \
	 	--pakdir=/usr/src/deb  \
		--maintainer="lagout " \
		--nodoc

cd /usr/src/deb
dpkg -i mariadb.deb


# Creating user MariaDB, keep the id between 750 and 900 by carefully
echo "Creating user MariaDB and copying configuration files"
useradd -c mysql -d /usr/local/mysql -M -r -s /bin/false -u 750  mysql
	chown mysql:mysql /usr/local/mysql #allow owner mysql to group mysql
	chown mysql:root /var/run/mysqld  #allow owner mysql to group root
	mkdir -p /usr/local/mysql/data/{InnoDB,bdd}
	
cd /usr/local/mysql
	/usr/local/mysql/scripts/mysql_install_db --user=mysql --no-defaults
	cd $execPath
	
cp ../config/mariadb/mysqld /etc/init.d/mysqld
	chmod +x /etc/init.d/mysqld
	cp ../config/systemd/mysqld.service  /etc/systemd/system/multi-user.target.wants/
	mv /etc/mysql/my.cnf /etc/mysql/my.cnf.default
	mv /usr/local/mysql/bin/mysql_secure_installation /usr/local/mysql/bin/mysql_secure_installation.hold
	
cp ../config/mariadb/mysql_secure_installation /usr/local/mysql/bin/mysql_secure_installation
	chmod +x /usr/local/mysql/bin/mysql_secure_installation
	
cp ../config/mariadb/my.cnf /usr/local/mysql/my.cnf
	chown -R mysql:mysql /usr/local/mysql
	#/etc/init.d/mysqld start
	systemctl enable mysqld.service
	systemctl start mysqld.service
sleep 5


